### ISSUE TITLE
Join requests not working

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#794]
Easily reproducible on local - sign up as a new mentor, request to join a dojo as a mentor. 

Get an error that says join request not found.

The join request is in the database correctly and I'm logged in as the founding champion.

Two reports of this in the last couple of days also - something to do with API version 2.0?

**Comment by mihaidma** [comment]
Can't reproduce it. Can I get more details please? Can you send me the request that fails?

**Comment by tangentfairy** [comment]
http://zen.coderdojo.com/api/2.0/dojos/accept-user-request is the request that returns the error

**Comment by mihaidma** [comment]
Made a fix for this. Will be added after merging with the user validation changes.

**Comment by ckiss** [comment]
@mihaidma @tangentfairy this should be fixed by the changes made here:
https://github.com/CoderDojo/cp-zen-platform/pull/749 & https://github.com/CoderDojo/cp-users-service/pull/171

**Comment by tangentfairy** [comment]
Thanks, will test this asap

**Comment by ckiss** [comment]
tested this and it's working fine now

**Comment by tangentfairy** [comment]
I still get this error, we'll have to take a look and make sure there's not something funny I am doing!

**Comment by mihaidma** [comment]
I tested the scenario that was reproducing this and seems that the issue is solved. Tested with `dojos-service` on `master`

**Comment by tangentfairy** [comment]
Working on those branches now
