### ISSUE TITLE
Event date showing as "invalid date" after event creation, impossible to set right

### ISSUE THREAD

**Issue by MMSequeira** [CoderDojo/community-platform#932]
When I try to create a new event in Zen, even though I select the date and time correctly (in this case 2016-03-12 and 03:00 pm to 06:00 pm), the date is set wrongly. When I check in the events listing, it appears as «invalid date». This makes it impossible to create new events. Can someone help? @dberesford, @dmk12 ?

**Comment by tangentfairy** [comment]
This was reported by @MMSequeira recently and I fixed the issue in the database. It seems it is a recurring issue. If you do a search in the events database for empty date objects it will confirm how many users are having this problem.

@adhorrig had experienced this locally last month also. @Wardormeur this would be our highest priority issue to resolve at the moment.

**Comment by Wardormeur** [comment]
This should have been solved, do you still experience it @MMSequeira  ?

**Comment by MMSequeira** [comment]
I was able to create last week's session without date problems.

**Comment by MMSequeira** [comment]
The issue occurred again. I've just created next saturday's event and the data is again "invalid date".

**Comment by MMSequeira** [comment]
I've tried to edit the event and change the date, but it was still shown as invalid. I changed browsers and used Zen in English, rather than in Portuguese, edited again the date, and the date was set correctly. Could it be a date localization problem?

**Comment by Wardormeur** [comment]
Ok thanks for the input, the localization should be definitely related

**Comment by Wardormeur** [comment]
Do you remember last time you tried and it worked if you were in Portuguese or not ?

**Comment by MMSequeira** [comment]
Can't remember. Sorry.

On Thu, Apr 7, 2016 at 5:07 PM, Wardormeur <notifications@github.com> wrote:

> Do you remember last time you tried and it worked if you were in
> Portuguese or not ?
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/CoderDojo/community-platform/issues/932#issuecomment-206972119>
>



-- 
Google+: mmsequeira@gmail.com
Mobile: +351 962 337 428
Skype: mmsequeira

<http://zen.coderdojo.com/dojo/pt/lisboa/lisbon/lisboa-lx-1>

**Comment by Wardormeur** [comment]
No worries :+1:

**Comment by DGuiloff** [comment]
Guillaume Feliciano referred me to this thread from the CoderDojo forum. I experienced the same issue, in English, from Chrome but with the added issue that each time I tried correcting the invalid date, it sent out a notice to all of our members. This happened several times before the date stuck (and before I noticed incorrect invites were continuing to go out). The only thing I can remember doing differently was choosing the time for the hour via the arrows vs trying to type them in before it worked. Even though I used the arrows, with the minutes I had to type them in because they were giving strange increments (:03 & :17). This all happened Monday 4/4.

**Comment by Wardormeur** [comment]
Hey there,
Were those event recurrent or one-time only ?

**Comment by MMSequeira** [comment]
One time only.

On Thu, Apr 14, 2016 at 2:10 PM, Wardormeur <notifications@github.com>
wrote:

> Hey there,
> Were those event recurrent or one-time only ?
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/CoderDojo/community-platform/issues/932#issuecomment-209935309>
>



-- 
Google+: mmsequeira@gmail.com
Mobile: +351 962 337 428
Skype: mmsequeira

<http://zen.coderdojo.com/dojo/pt/lisboa/lisbon/lisboa-lx-1>

**Comment by Wardormeur** [comment]
Sorry to be a pain, but could you tell me how the date displays on your browser?
Is it like dd/MM/YYYY or does it displays differently ?

**Comment by DGuiloff** [comment]
Same here, single, non-recurring event. 

This is what the date/time display looks like during creation: http://grab.by/PtPU

**Comment by MMSequeira** [comment]
I tried in different browsers, and with different default locales defined
in my Mac (Chrome, Firefox, Opera, and perheps Safari). I tried to set the
Portuguese locale, where dates are shown as yyyy-mm-dd, and also tried the
US locale, with mm/dd/yyyy. I tried Windows (Chrome) with the Portuguese
and US locales. None worked.

I managed to create our next session using Chrome on Ubuntu and my son's
Zen account. The locale in his Ubuntu account is US, I think. I'm not sure,
though.

On Thu, Apr 14, 2016 at 2:31 PM, Wardormeur <notifications@github.com>
wrote:

> Sorry to be a pain, but could you tell me how the date displays on your
> browser?
> Is it like dd/MM/YYYY or does it displays differently ?
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/CoderDojo/community-platform/issues/932#issuecomment-209941573>
>



-- 
Google+: mmsequeira@gmail.com
Mobile: +351 962 337 428
Skype: mmsequeira

<http://zen.coderdojo.com/dojo/pt/lisboa/lisbon/lisboa-lx-1>

**Comment by Wardormeur** [comment]
I've been changing locales and date format without success to reproduce the issue alas.
We're using a quite outdated version of the lib, which seems to be flawed by a couple of problems when it comes to dates. We'll schedule an update of those and also provide a better way for you guys to report when we're debugging a specific issue with a specific dump of the different objects that can affect it.
Thanks for your patience :+1:

**Comment by DanielBrierton** [comment]
Managed to reproduce this. It happens when you delete all the text from one of the input fields of the time picker. This kicks the moment date in memory to "Invalid Date" because the time picker returns null if it's invalid. Simple fix was to just to not update fixedStartDateTime/fixedEndDateTime when this scenario occurs.

I've created a pull request with the fix: CoderDojo/cp-zen-platform#866

**Comment by Wardormeur** [comment]
Bug fixed by @DanielBrierton :+1: Good catch
I'm leaving this opened for a couple of days to get any feedback regarding the fix to see if it covers everybody's issues

**Comment by DanielBrierton** [comment]
Can we close this now? No further reports of this since.

**Comment by Wardormeur** [comment]
yup.
